### ISSUE TITLE
fcs files

### ISSUE THREAD

**Issue by lmanchon** [mlux86/flowLearn#1]
--Hi, 

i have 2 fcs files and i don't really understand which commands i need to run to compare populations between these 2 files.
For example: file_one.fcs and file_two.fcs
Can you try to make a ready to use pipeline with commands using these 2 files ?
Thank you --

**Comment by ryanrbrinkman** [comment]
It not clear ou are using ht right tool for the job. The vignette has a fully worked example.

On Jan 24, 2019, at 12:52 PM, lmanchon <notifications@github.com<mailto:notifications@github.com>> wrote:


--Hi,

i have 2 fcs files and i don't really understand which commands i need to run to compare populations between these 2 files.
For example: file_one.fcs and file_two.fcs
Can you try to make a ready to use pipeline with commands using these 2 files ?
Thank you --

**Comment by lmanchon** [comment]
yes, i have read the vignette, but for example if i need to construct a DensityData object using two fcs files embedded in the attached file here, and using only 3 channels from these 2 files: FL1H,FL2H and FL3H. 
Which commands i need to run ?
thank you --

[FACS.zip](https://github.com/mlux86/flowLearn/files/2795974/FACS.zip)

**Comment by mlx404** [comment]
Dear @lmanchon ,
I'm afraid, I do not have the resources to help you with your problem - the vignette should be pretty self-explanatory. If you have any specific issues or questions, feel free to report them.
In this case, however, I will close the issue as it is not very specific.
Good luck,
Markus
